---
version: 0.2

env:
  parameter-store:
    ssh_private_key: "ssh_private_key"

phases:
  pre_build:
    commands:
      # ec2 private key setup
      - pwd
      - echo "${ssh_private_key}" > ~/.ssh/id_rsa
      - chmod 0700 ~/.ssh
      - chmod 0600 ~/.ssh/id_rsa
      - ls -ltr ~/.ssh
      - ls -ltr $CODEBUILD_SRC_DIR
      - which aws
      - aws --version
      - df -h
      # cloudformation tempate check
      - sh cfn_template_check.sh
      # ansible setup
      # amazon linuxでansibleをインストールしようとしたらうまくいかなかったのでubuntuで妥協した
      - apt-get update -y
      - apt-get install software-properties-common -y
      - apt-add-repository ppa:ansible/ansible -y
      - apt-get install ansible -y
      - ansible  --version
      - apt-get install openssh-client -y
      - ansible-playbook --version
      - apt install ansible-lint -y
      - ansible-lint --version
      # cloudformationのコードチェック
      # - aws cloudformation validate-template --template-body file://ansible-cf-mattermost.yml
      # ansibleのコードチェック
      - ansible-lint site.yml
      # EC2の起動チェック。pingの応答を確認する。
      - ansible --ssh-common-args="-F ssh_config" -i inventories/prod -m ping all
      
  build:
    commands:
        # - ssh -vvv -o StrictHostKeyChecking=no ec2-18-183-86-230.ap-northeast-1.compute.amazonaws.com hostname
        # - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@ec2-54-168-212-100.ap-northeast-1.compute.amazonaws.com -p 22 "pwd;ls -alF;hostname"
        # - ansible-playbook -i hosts/inventory.yml ./setup.yml
        - ansible-playbook --ssh-common-args="-F ssh_config" -i inventories/prod site.yml
  post_build:
    commands:
      - echo "Now Finished Privisioning by Ansible"