---
version: 0.2

# こうするとaws パラメータストアからデータを取得できるようになる
env:
  parameter-store:
    ssh_private_key: "ssh_private_key"

phases:
  pre_build:
    commands:
      # ec2 private key setup
      - pwd
      - echo "${ssh_private_key}" > ~/.ssh/id_rsa
      - chmod 0700 ~/.ssh
      - chmod 0600 ~/.ssh/id_rsa
      - ls -ltr ~/.ssh
      - md5sum ~/.ssh/id_rsa
      - tail -n 5 id_rsa
      - ls -ltr $CODEBUILD_SRC_DIR
      - which aws
      - aws --version
      - df -h
      # cloudformation tempate check
      - sh cfn_template_check.sh
      # ansible setup
      # amazon linuxでansibleをインストールしようとしたらうまくいかなかったのでubuntuで妥協した
      - apt-get update -y
      - apt-get install software-properties-common -y
      - apt-add-repository ppa:ansible/ansible -y
      - apt-get install ansible -y
      - ansible  --version
      - apt-get install openssh-client -y
      - ansible-playbook --version
      - apt install ansible-lint -y
      - ansible-lint --version
      # cloudformationのコードチェック
      # - aws cloudformation validate-template --template-body file://ansible-cf-mattermost.yml
      # ansibleのコードチェック
      # yaml: truthy value should be one of [false, true] (truthy) が解決できないので一旦コメント
      - ansible-lint site.yml
      # EC2の起動チェック。pingの応答を確認する。
      # - ansible --ssh-common-args="-F ssh_config" -i inventories/prod -m ping all
      
  build:
    commands:
        - ansible-playbook --ssh-common-args="-F ssh_config" -i inventories/prod site.yml
  post_build:
    commands:
      - echo "Now Finished Privisioning by Ansible"