AWSTemplateFormatVersion: "2010-09-09"

Description: create rds

#パラメータ
Parameters:
  vpcid:
    Type: AWS::EC2::VPC::Id
    Description: Enter vpcid

  subnetid1: 
    Type: AWS::EC2::Subnet::Id
    Description: Enter RDS subnetid

  subnetid2: 
    Type: AWS::EC2::Subnet::Id
    Description: Enter RDS subnetid

  rdssubnetgroupname:
    Type: String
    Description: Enter RDS subnet groupname

  rdsdbname:
    Type: String
    Description: Enter RDS DBname

  rdsusername:
    Type: String
    Description: Enter RDS username
    AllowedPattern: '[a-zA-Z0-9]*'

  rdspassword: 
    Type: String
    Description: Enter RDS password
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'

#リソース
Resources:
  lambdasecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: lambda-securitygroup
      SecurityGroupEgress: 
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref vpcid

  rdssecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: rds-securitygroup
      SecurityGroupEgress: 
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref lambdasecuritygroup
      VpcId: !Ref vpcid

  rdssubnetgroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: rdssubnetgroup
      SubnetIds:  
        - !Ref subnetid1
        - !Ref subnetid2
      DBSubnetGroupName: !Ref rdssubnetgroupname
      Tags: 
        - Key: Name
          Value: rdssubnetgroup

  rdsinstance:  
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: 
        !Ref rdssubnetgroup
      DBName: jimbot3rds
      Engine: mysql
      EngineVersion: "5.7.34"
      MasterUsername: jimbot3
      MasterUserPassword: xxxxxxxx
      StorageType: gp2
      Tags:
        - Key: Name
          Value: rdsinstance
      VPCSecurityGroups: 
        - !Ref rdssecuritygroup