Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "RDSName" #この名前を使ってLambdaはエンドポイント名を取得します
      DBName: jimbot3rds
      Engine: MySQL
      MasterUsername: jimbot3
      DBInstanceClass: db.t2.micro 
      AllocatedStorage: '20'
      MasterUserPassword: xxxxxxxx
      VPCSecurityGroups:
      - !GetAtt DBSecurityGroup.GroupId

  Mylambda: 
    Type: "Custom::ExcuteLambda"
    Version: "1.0"
    Properties: 
      ServiceToken: "arn:aws:lambda:ap-northeast-1:414328432170:function:myfunction" #ここにLambdaのARNを入力します
      RequestType: Create
    DependsOn: DBInstance

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 22only
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: "0.0.0.0/0"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0