---
- name: yum install multi-list
  yum:
    name:
      - git
      - nc
    # state: latest
    state: present
- name: yum install amazon-cloudwatch-agent
  yum:
    name:
      - amazon-cloudwatch-agent
    # state: latest
    state: present
- name: yum install epel-release-latest-7.noarch.rpm
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    # state: latest
    state: present
- name: yum install collectd
  yum:
    name:
      - collectd
    # state: latest
    state: present

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: generate cloud watch config file
  copy:
    src: cloud_watch_config.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0755'

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: cloud watch restart
  systemd:
    name: amazon-cloudwatch-agent
    # daemon_reload: yes
    daemon_reload: true
    state: restarted
    enabled: true
    # enabled: yes
